version: '2'
services:
  # DBサーバ
  db01:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      # DBにseichiassistスキーマと、playerdataテーブルを作成する
      - ./files/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seichiassist

  # Webサーバ
  web01:
    build: ./web
    image: web:24
    ports:
      - "80:80"
    links:
      - "db01:db01"
    volumes:
      # ソース一式をドキュメントルートに配置
      - ../:/var/www/SeichiRanking
      # apacheのログファイルをマウント(ホストPCで手軽に見れ流ようにする)
      - ./var/logs:/var/log/httpd
      # apacheの設定ファイルをマウント
      - ./files/apache_conf/00_virtualhost.conf:/etc/httpd/conf.d/00_virtualhost.conf
