version: '3'
services:
  db01:
    image: mariadb:10.6.5
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./docker/config/mysql:/etc/mysql/conf.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seichiassist
      TZ: Asia/Tokyo

  web01:
    build: .
    # image: web:24
    ports:
      - "80:80"

volumes:
  mysql_volume:
