version: '3'
services:

  app:
    image: docker pull ghcr.io/giganticminecraft/seichi-ranking:master

  web:
    image: nginx:mainline
    volumes:
      - .:/var/www/html
      - ./docker/config/nginx/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
        - app
