version: '3'
services:
  web:
    image: nginx:mainline
    volumes:
      - .:/var/www/html
      - ./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
    environment:
      - TZ=Asia/Tokyo

  app:
    build: .
    env_file:
      - .env

  db:
    image: mariadb:10.6.7
    ports:
      - 3306:3306
    restart: always
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=root
