version: '3'
services:
  db:
    image: mariadb:10.6.5
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./docker/config/mysql:/etc/mysql/conf.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seichiassist
      TZ: Asia/Tokyo

  app:
    build: .
    depends_on:
        - db

  web:
    image: nginx:mainline
    volumes:
      - .:/var/www/html
      - ./docker/nginx/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
        - app

volumes:
  mysql_volume:
