version: '3'
services:

  app:
    image: ghcr.io/giganticminecraft/seichi-ranking:master
    volumes:
      - .env:/var/www/html/.env
    depends_on:
        - db

  web:
    image: nginx:mainline
    volumes:
      - .:/var/www/html
      - ./docker/config/nginx/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
        - app
