version: '3'
services:

  app:
    build: .
    depends_on:
        - db
    environment:
      LOG_CHANNEL: stdout

  web:
    image: nginx:mainline
    volumes:
      - .:/var/www/html
      - ./docker/config/nginx/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
        - app

volumes:
  mysql_volume:
