DROP SCHEMA IF EXISTS seichiassist;
CREATE SCHEMA seichiassist;
USE seichiassist;

DROP TABLE IF EXISTS playerdata;
CREATE TABLE `playerdata` (
 `name` varchar(30) DEFAULT NULL,
 `uuid` varchar(128) DEFAULT NULL,
 `effectflag` tinyint(4) DEFAULT '0',
 `minestackflag` tinyint(1) DEFAULT '1',
 `messageflag` tinyint(1) DEFAULT '0',
 `activemineflagnum` int(11) DEFAULT '0',
 `assaultflag` tinyint(1) DEFAULT '0',
 `activeskilltype` int(11) DEFAULT '0',
 `activeskillnum` int(11) DEFAULT '1',
 `assaultskilltype` int(11) DEFAULT '0',
 `assaultskillnum` int(11) DEFAULT '0',
 `arrowskill` int(11) DEFAULT '0',
 `multiskill` int(11) DEFAULT '0',
 `breakskill` int(11) DEFAULT '0',
 `condenskill` int(11) DEFAULT '0',
 `effectnum` int(11) DEFAULT '0',
 `gachapoint` int(11) DEFAULT '0',
 `gachaflag` tinyint(1) DEFAULT '1',
 `level` int(11) DEFAULT '1',
 `numofsorryforbug` int(11) DEFAULT '0',
 `inventory` blob,
 `rgnum` int(11) DEFAULT '0',
 `totalbreaknum` bigint(20) DEFAULT '0',
 `lastquit` datetime DEFAULT NULL,
 `displayTypeLv` tinyint(1) DEFAULT '1',
 `displayTitleNo` int(11) DEFAULT '0',
 `TitleFlags` text,
 `giveachvNo` int(11) DEFAULT '0',
 `playtick` int(11) DEFAULT '0',
 `killlogflag` tinyint(1) DEFAULT '0',
 `worldguardlogflag` tinyint(1) DEFAULT '1',
 `multipleidbreakflag` tinyint(1) DEFAULT '0',
 `pvpflag` tinyint(1) DEFAULT '0',
 `loginflag` tinyint(1) DEFAULT '0',
 `p_vote` int(11) DEFAULT '0',
 `p_givenvote` int(11) DEFAULT '0',
 `effectpoint` int(11) DEFAULT '0',
 `premiumeffectpoint` int(11) DEFAULT '0',
 `mana` double DEFAULT '0',
 `expvisible` tinyint(1) DEFAULT '1',
 `totalexp` int(11) DEFAULT '0',
 `expmarge` tinyint(3) unsigned DEFAULT '0',
 `shareinv` blob,
 `everysound` tinyint(1) DEFAULT '1',
 `build_lv` int(11) DEFAULT '1',
 `build_count` int(11) DEFAULT '0',
 `build_count_flg` tinyint(3) unsigned DEFAULT '0',
 `lastcheckdate` varchar(12) DEFAULT NULL,
 `ChainJoin` int(11) DEFAULT '0',
 `TotalJoin` int(11) DEFAULT '0',
 `displayTitle1No` int(11) DEFAULT '0',
 `displayTitle2No` int(11) DEFAULT '0',
 `displayTitle3No` int(11) DEFAULT '0',
 `achvPointMAX` int(11) DEFAULT '0',
 `achvPointUSE` int(11) DEFAULT '0',
 `achvChangenum` int(11) DEFAULT '0',
 UNIQUE KEY `name` (`name`),
 UNIQUE KEY `uuid` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO playerdata (name, uuid, totalbreaknum, build_count, p_vote)
VALUES ("TestUser", "00000000", 999, 888, 777);