name: "SeichiRankingのコンテナイメージをビルド"

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USER_NAME: giganticminecraft
      IMAGE_NAME: seichi-ranking
    steps:
    - uses: actions/checkout@v2
      name: checkout
    - uses: docker/setup-buildx-action@v1
      name: Set up Docker Buildx
    - uses: docker/login-action@v1
      name: Login to GitHub Container Registry
      with:
        registry: ghcr.io
        username: giganticminecraft
        password: ${{ secrets.GITHUB_TOKEN  }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
