name: "SeichiRankingのコンテナイメージをビルド"

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      image_name: seichi-ranking
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx
      - uses: docker/login-action@v1
        name: Login to GitHub Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN  }}
      # Docker does not allow uppercase letters for image name, so we must replace repository_owner and so on
      - id: prepare_image_id
        name: Prepare image id's components
        run: |
          lowercase_id=ghcr.io/${{ github.repository_owner }}/${{ env.image_name }}
          echo "::set-output name=lowercase_id::$(echo $lowercase_id | tr '[A-Z]' '[a-z]')"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ steps.prepare_image_id.outputs.lowercase_id }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
