name: PHP Composer

on:
  push:
    branches: [ develop ]
    paths-ignore:
      - '.github/workflows/*'
      - 'docker/*'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'docker-compose.prd.yml'
  pull_request:
    branches: [ master, develop ]
    paths-ignore:
      - '.github/workflows/*'
      - 'docker/*'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'docker-compose.prd.yml'

jobs:
  phplint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # It seems that GitHub-hosted runner has multiple php versions.
    # We must ensure use php8.1, as the software requires.
    # See also: https://github.com/actions/virtual-environments/blob/ubuntu20/20220111.1/images/linux/Ubuntu2004-Readme.md
    - name: Switch to php8.1
      run: sudo update-alternatives --set php /usr/bin/php8.1
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Run phplint
      uses: overtrue/phplint@8.1
      with:
        path: .
        options: --exclude=vendor
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
